package com.bonepl.chromaleague.hud;

import com.bonepl.razersdk.sdk.RzKey;

import java.util.List;

import static com.bonepl.razersdk.sdk.RzKey.*;

public final class PredefinedKeySets {
    public static final List<RzKey> BLACKWIDOW_FIRST_ROW = List.of(RZKEY_ESC, RZKEY_F1, RZKEY_F2, RZKEY_F3, RZKEY_F4, RZKEY_F5, RZKEY_F6, RZKEY_F7,
            RZKEY_F8, RZKEY_F9, RZKEY_F10, RZKEY_F11, RZKEY_F12, RZKEY_PRINTSCREEN, RZKEY_SCROLL, RZKEY_PAUSE);
    public static final List<RzKey> BLACKWIDOW_SECOND_ROW = List.of(RZKEY_MACRO1, RZKEY_TILDE, RZKEY_1, RZKEY_2,
            RZKEY_3, RZKEY_4, RZKEY_5, RZKEY_6, RZKEY_7, RZKEY_8, RZKEY_9, RZKEY_0, RZKEY_HYPHEN, RZKEY_EQUALS,
            RZKEY_BACKSPACE, RZKEY_INSERT, RZKEY_HOME, RZKEY_PAGEUP, RZKEY_NUMLOCK, RZKEY_NUMPAD_DIVIDE,
            RZKEY_NUMPAD_MULTIPLY, RZKEY_NUMPAD_SUBTRACT);
    public static final List<RzKey> BLACKWIDOW_THIRD_ROW = List.of(RZKEY_MACRO2, RZKEY_TAB, RZKEY_Q, RZKEY_W,
            RZKEY_E, RZKEY_R, RZKEY_T, RZKEY_Y, RZKEY_U, RZKEY_I, RZKEY_O, RZKEY_P, RZKEY_SQUARE_BRACKET_LEFT, RZKEY_SQUARE_BRACKET_RIGHT, RZKEY_BACKSLASH,
            RZKEY_DELETE, RZKEY_END, RZKEY_PAGEDOWN, RZKEY_NUMPAD7, RZKEY_NUMPAD8, RZKEY_NUMPAD9, RZKEY_NUMPAD_ADD);
    public static final List<RzKey> BLACKWIDOW_FOURTH_ROW = List.of(RZKEY_MACRO3, RZKEY_CAPSLOCK, RZKEY_A,
            RZKEY_S, RZKEY_D, RZKEY_F, RZKEY_G, RZKEY_H, RZKEY_J, RZKEY_K, RZKEY_L, RZKEY_SEMICOLON, RZKEY_APOSTROPHE, RZKEY_ENTER,
            RZKEY_NUMPAD4, RZKEY_NUMPAD5, RZKEY_NUMPAD6, RZKEY_NUMPAD_ADD);
    public static final List<RzKey> BLACKWIDOW_FIFTH_ROW = List.of(RZKEY_MACRO4, RZKEY_LSHIFT, RZKEY_Z, RZKEY_X,
            RZKEY_C, RZKEY_V, RZKEY_B, RZKEY_N, RZKEY_M, RZKEY_COMA, RZKEY_DOT, RZKEY_SLASH, RZKEY_RSHIFT,
            RZKEY_UP, RZKEY_NUMPAD1, RZKEY_NUMPAD2, RZKEY_NUMPAD3, RZKEY_NUMPAD_ENTER);
    public static final List<RzKey> BLACKWIDOW_SIXTH_ROW = List.of(RZKEY_MACRO5, RZKEY_LCTRL, RZKEY_LWIN,
            RZKEY_LALT, RZKEY_SPACE, RZKEY_RALT, RZKEY_FN, RZKEY_RMENU, RZKEY_RCTRL, RZKEY_LEFT, RZKEY_DOWN,
            RZKEY_RIGHT, RZKEY_NUMPAD0, RZKEY_NUMPAD_DECIMAL, RZKEY_NUMPAD_ENTER);
    public static final List<RzKey> BLACKWIDOW_FUNCTIONAL
            = List.of(RZKEY_PRINTSCREEN, RZKEY_SCROLL, RZKEY_PAUSE,
            RZKEY_INSERT, RZKEY_HOME, RZKEY_PAGEUP,
            RZKEY_DELETE, RZKEY_END, RZKEY_PAGEDOWN);
    public static final List<RzKey> FIRST_NUMPAD_COLUMN
            = List.of(RZKEY_NUMLOCK, RZKEY_NUMPAD7, RZKEY_NUMPAD4, RZKEY_NUMPAD1, RZKEY_NUMPAD0);
    public static final List<RzKey> SECOND_NUMPAD_COLUMN
            = List.of(RZKEY_NUMPAD_DIVIDE, RZKEY_NUMPAD8, RZKEY_NUMPAD5, RZKEY_NUMPAD2, RZKEY_NUMPAD0);
    public static final List<RzKey> THIRD_NUMPAD_COLUMN
            = List.of(RZKEY_NUMPAD_MULTIPLY, RZKEY_NUMPAD9, RZKEY_NUMPAD6, RZKEY_NUMPAD3, RZKEY_NUMPAD_DECIMAL);
    public static final List<RzKey> FOURTH_NUMPAD_COLUMN
            = List.of(RZKEY_NUMPAD_SUBTRACT, RZKEY_NUMPAD_ADD, RZKEY_NUMPAD_ENTER);

    private PredefinedKeySets() {
    }
}
