/**
 * Razer Chroma SDK keys mapping
 */
export enum RzKey {
    RZKEY_ESC,
    RZKEY_F1,
    RZKEY_F2,
    RZKEY_F3,
    RZKEY_F4,
    RZKEY_F5,
    RZKEY_F6,
    RZKEY_F7,
    RZKEY_F8,
    RZKEY_F9,
    RZKEY_F10,
    RZKEY_F11,
    RZKEY_F12,
    RZKEY_1,
    RZKEY_2,
    RZKEY_3,
    RZKEY_4,
    RZKEY_5,
    RZKEY_6,
    RZKEY_7,
    RZKEY_8,
    RZKEY_9,
    RZKEY_0,
    RZKEY_A,
    RZKEY_B,
    RZKEY_C,
    RZKEY_D,
    RZKEY_E,
    RZKEY_F,
    RZKEY_G,
    RZKEY_H,
    RZKEY_I,
    RZKEY_J,
    RZKEY_K,
    RZKEY_L,
    RZKEY_M,
    RZKEY_N,
    RZKEY_O,
    RZKEY_P,
    RZKEY_Q,
    RZKEY_R,
    RZKEY_S,
    RZKEY_T,
    RZKEY_U,
    RZKEY_V,
    RZKEY_W,
    RZKEY_X,
    RZKEY_Y,
    RZKEY_Z,
    RZKEY_NUMLOCK,
    RZKEY_NUMPAD0,
    RZKEY_NUMPAD1,
    RZKEY_NUMPAD2,
    RZKEY_NUMPAD3,
    RZKEY_NUMPAD4,
    RZKEY_NUMPAD5,
    RZKEY_NUMPAD6,
    RZKEY_NUMPAD7,
    RZKEY_NUMPAD8,
    RZKEY_NUMPAD9,
    RZKEY_NUMPAD_DIVIDE,
    RZKEY_NUMPAD_MULTIPLY,
    RZKEY_NUMPAD_SUBTRACT,
    RZKEY_NUMPAD_ADD,
    RZKEY_NUMPAD_ENTER,
    RZKEY_NUMPAD_DECIMAL,
    RZKEY_PRINTSCREEN,
    RZKEY_SCROLL,
    RZKEY_PAUSE,
    RZKEY_INSERT,
    RZKEY_HOME,
    RZKEY_PAGEUP,
    RZKEY_DELETE,
    RZKEY_END,
    RZKEY_PAGEDOWN,
    RZKEY_UP,
    RZKEY_LEFT,
    RZKEY_DOWN,
    RZKEY_RIGHT,
    RZKEY_TAB,
    RZKEY_CAPSLOCK,
    RZKEY_BACKSPACE,
    RZKEY_ENTER,
    RZKEY_LCTRL,
    RZKEY_LWIN,
    RZKEY_LALT,
    RZKEY_SPACE,
    RZKEY_RALT,
    RZKEY_FN,
    RZKEY_RMENU,
    RZKEY_RCTRL,
    RZKEY_LSHIFT,
    RZKEY_RSHIFT,
    RZKEY_MACRO1,
    RZKEY_MACRO2,
    RZKEY_MACRO3,
    RZKEY_MACRO4,
    RZKEY_MACRO5,
    RZKEY_TILDE,
    RZKEY_HYPHEN,
    RZKEY_EQUALS,
    RZKEY_SQUARE_BRACKET_LEFT,
    RZKEY_SQUARE_BRACKET_RIGHT,
    RZKEY_BACKSLASH,
    RZKEY_SEMICOLON,
    RZKEY_APOSTROPHE,
    RZKEY_COMA,
    RZKEY_DOT,
    RZKEY_SLASH,
    RZKEY_EUR_1,
    RZKEY_EUR_2,
    RZKEY_JPN_1,
    RZKEY_JPN_2,
    RZKEY_JPN_3,
    RZKEY_JPN_4,
    RZKEY_JPN_5,
    RZKEY_KOR_1,
    RZKEY_KOR_2,
    RZKEY_KOR_3,
    RZKEY_KOR_4,
    RZKEY_KOR_5,
    RZKEY_KOR_6,
    RZKEY_KOR_7,
}

export interface RzKeyPosition {
    row: number;
    col: number;
}

export const RZ_KEY_POSITIONS: ReadonlyMap<RzKey, RzKeyPosition> = new Map<RzKey, RzKeyPosition>([
    [RzKey.RZKEY_ESC, { row: 0, col: 1 }],
    [RzKey.RZKEY_F1, { row: 0, col: 3 }],
    [RzKey.RZKEY_F2, { row: 0, col: 4 }],
    [RzKey.RZKEY_F3, { row: 0, col: 5 }],
    [RzKey.RZKEY_F4, { row: 0, col: 6 }],
    [RzKey.RZKEY_F5, { row: 0, col: 7 }],
    [RzKey.RZKEY_F6, { row: 0, col: 8 }],
    [RzKey.RZKEY_F7, { row: 0, col: 9 }],
    [RzKey.RZKEY_F8, { row: 0, col: 10 }],
    [RzKey.RZKEY_F9, { row: 0, col: 11 }],
    [RzKey.RZKEY_F10, { row: 0, col: 12 }],
    [RzKey.RZKEY_F11, { row: 0, col: 13 }],
    [RzKey.RZKEY_F12, { row: 0, col: 14 }],
    [RzKey.RZKEY_1, { row: 1, col: 2 }],
    [RzKey.RZKEY_2, { row: 1, col: 3 }],
    [RzKey.RZKEY_3, { row: 1, col: 4 }],
    [RzKey.RZKEY_4, { row: 1, col: 5 }],
    [RzKey.RZKEY_5, { row: 1, col: 6 }],
    [RzKey.RZKEY_6, { row: 1, col: 7 }],
    [RzKey.RZKEY_7, { row: 1, col: 8 }],
    [RzKey.RZKEY_8, { row: 1, col: 9 }],
    [RzKey.RZKEY_9, { row: 1, col: 10 }],
    [RzKey.RZKEY_0, { row: 1, col: 11 }],
    [RzKey.RZKEY_A, { row: 3, col: 2 }],
    [RzKey.RZKEY_B, { row: 4, col: 7 }],
    [RzKey.RZKEY_C, { row: 4, col: 5 }],
    [RzKey.RZKEY_D, { row: 3, col: 4 }],
    [RzKey.RZKEY_E, { row: 2, col: 4 }],
    [RzKey.RZKEY_F, { row: 3, col: 5 }],
    [RzKey.RZKEY_G, { row: 3, col: 6 }],
    [RzKey.RZKEY_H, { row: 3, col: 7 }],
    [RzKey.RZKEY_I, { row: 2, col: 9 }],
    [RzKey.RZKEY_J, { row: 3, col: 8 }],
    [RzKey.RZKEY_K, { row: 3, col: 9 }],
    [RzKey.RZKEY_L, { row: 3, col: 10 }],
    [RzKey.RZKEY_M, { row: 4, col: 9 }],
    [RzKey.RZKEY_N, { row: 4, col: 8 }],
    [RzKey.RZKEY_O, { row: 2, col: 10 }],
    [RzKey.RZKEY_P, { row: 2, col: 11 }],
    [RzKey.RZKEY_Q, { row: 2, col: 2 }],
    [RzKey.RZKEY_R, { row: 2, col: 5 }],
    [RzKey.RZKEY_S, { row: 3, col: 3 }],
    [RzKey.RZKEY_T, { row: 2, col: 6 }],
    [RzKey.RZKEY_U, { row: 2, col: 8 }],
    [RzKey.RZKEY_V, { row: 4, col: 6 }],
    [RzKey.RZKEY_W, { row: 2, col: 3 }],
    [RzKey.RZKEY_X, { row: 4, col: 4 }],
    [RzKey.RZKEY_Y, { row: 2, col: 7 }],
    [RzKey.RZKEY_Z, { row: 4, col: 3 }],
    [RzKey.RZKEY_NUMLOCK, { row: 1, col: 18 }],
    [RzKey.RZKEY_NUMPAD0, { row: 5, col: 19 }],
    [RzKey.RZKEY_NUMPAD1, { row: 4, col: 18 }],
    [RzKey.RZKEY_NUMPAD2, { row: 4, col: 19 }],
    [RzKey.RZKEY_NUMPAD3, { row: 4, col: 20 }],
    [RzKey.RZKEY_NUMPAD4, { row: 3, col: 18 }],
    [RzKey.RZKEY_NUMPAD5, { row: 3, col: 19 }],
    [RzKey.RZKEY_NUMPAD6, { row: 3, col: 20 }],
    [RzKey.RZKEY_NUMPAD7, { row: 2, col: 18 }],
    [RzKey.RZKEY_NUMPAD8, { row: 2, col: 19 }],
    [RzKey.RZKEY_NUMPAD9, { row: 2, col: 20 }],
    [RzKey.RZKEY_NUMPAD_DIVIDE, { row: 1, col: 19 }],
    [RzKey.RZKEY_NUMPAD_MULTIPLY, { row: 1, col: 20 }],
    [RzKey.RZKEY_NUMPAD_SUBTRACT, { row: 1, col: 21 }],
    [RzKey.RZKEY_NUMPAD_ADD, { row: 2, col: 21 }],
    [RzKey.RZKEY_NUMPAD_ENTER, { row: 4, col: 21 }],
    [RzKey.RZKEY_NUMPAD_DECIMAL, { row: 5, col: 20 }],
    [RzKey.RZKEY_PRINTSCREEN, { row: 0, col: 15 }],
    [RzKey.RZKEY_SCROLL, { row: 0, col: 16 }],
    [RzKey.RZKEY_PAUSE, { row: 0, col: 17 }],
    [RzKey.RZKEY_INSERT, { row: 1, col: 15 }],
    [RzKey.RZKEY_HOME, { row: 1, col: 16 }],
    [RzKey.RZKEY_PAGEUP, { row: 1, col: 17 }],
    [RzKey.RZKEY_DELETE, { row: 2, col: 15 }],
    [RzKey.RZKEY_END, { row: 2, col: 16 }],
    [RzKey.RZKEY_PAGEDOWN, { row: 2, col: 17 }],
    [RzKey.RZKEY_UP, { row: 4, col: 16 }],
    [RzKey.RZKEY_LEFT, { row: 5, col: 15 }],
    [RzKey.RZKEY_DOWN, { row: 5, col: 16 }],
    [RzKey.RZKEY_RIGHT, { row: 5, col: 17 }],
    [RzKey.RZKEY_TAB, { row: 2, col: 1 }],
    [RzKey.RZKEY_CAPSLOCK, { row: 3, col: 1 }],
    [RzKey.RZKEY_BACKSPACE, { row: 1, col: 14 }],
    [RzKey.RZKEY_ENTER, { row: 3, col: 14 }],
    [RzKey.RZKEY_LCTRL, { row: 5, col: 1 }],
    [RzKey.RZKEY_LWIN, { row: 5, col: 2 }],
    [RzKey.RZKEY_LALT, { row: 5, col: 3 }],
    [RzKey.RZKEY_SPACE, { row: 5, col: 7 }],
    [RzKey.RZKEY_RALT, { row: 5, col: 11 }],
    [RzKey.RZKEY_FN, { row: 5, col: 12 }],
    [RzKey.RZKEY_RMENU, { row: 5, col: 13 }],
    [RzKey.RZKEY_RCTRL, { row: 5, col: 14 }],
    [RzKey.RZKEY_LSHIFT, { row: 4, col: 1 }],
    [RzKey.RZKEY_RSHIFT, { row: 4, col: 14 }],
    [RzKey.RZKEY_MACRO1, { row: 1, col: 0 }],
    [RzKey.RZKEY_MACRO2, { row: 2, col: 0 }],
    [RzKey.RZKEY_MACRO3, { row: 3, col: 0 }],
    [RzKey.RZKEY_MACRO4, { row: 4, col: 0 }],
    [RzKey.RZKEY_MACRO5, { row: 5, col: 0 }],
    [RzKey.RZKEY_TILDE, { row: 1, col: 1 }],
    [RzKey.RZKEY_HYPHEN, { row: 1, col: 12 }],
    [RzKey.RZKEY_EQUALS, { row: 1, col: 13 }],
    [RzKey.RZKEY_SQUARE_BRACKET_LEFT, { row: 2, col: 12 }],
    [RzKey.RZKEY_SQUARE_BRACKET_RIGHT, { row: 2, col: 13 }],
    [RzKey.RZKEY_BACKSLASH, { row: 2, col: 14 }],
    [RzKey.RZKEY_SEMICOLON, { row: 3, col: 11 }],
    [RzKey.RZKEY_APOSTROPHE, { row: 3, col: 12 }],
    [RzKey.RZKEY_COMA, { row: 4, col: 10 }],
    [RzKey.RZKEY_DOT, { row: 4, col: 11 }],
    [RzKey.RZKEY_SLASH, { row: 4, col: 12 }],
    [RzKey.RZKEY_EUR_1, { row: 3, col: 13 }],
    [RzKey.RZKEY_EUR_2, { row: 4, col: 2 }],
    [RzKey.RZKEY_JPN_1, { row: 0, col: 21 }],
    [RzKey.RZKEY_JPN_2, { row: 4, col: 13 }],
    [RzKey.RZKEY_JPN_3, { row: 5, col: 4 }],
    [RzKey.RZKEY_JPN_4, { row: 5, col: 9 }],
    [RzKey.RZKEY_JPN_5, { row: 5, col: 10 }],
    [RzKey.RZKEY_KOR_1, { row: 0, col: 21 }],
    [RzKey.RZKEY_KOR_2, { row: 3, col: 13 }],
    [RzKey.RZKEY_KOR_3, { row: 4, col: 2 }],
    [RzKey.RZKEY_KOR_4, { row: 4, col: 13 }],
    [RzKey.RZKEY_KOR_5, { row: 5, col: 4 }],
    [RzKey.RZKEY_KOR_6, { row: 5, col: 9 }],
    [RzKey.RZKEY_KOR_7, { row: 5, col: 10 }],
]);

/** Get all RzKey enum values */
export function getRzKeyValues(): RzKey[] {
    return Object.values(RzKey).filter((v): v is RzKey => typeof v === 'number');
}

/** Get row for a given RzKey */
export function getRow(key: RzKey): number {
    return RZ_KEY_POSITIONS.get(key)!.row;
}

/** Get column for a given RzKey */
export function getColumn(key: RzKey): number {
    return RZ_KEY_POSITIONS.get(key)!.col;
}
